event_management.settings:
  type: config_object
  label: 'Event Management Settings'
  mapping:
    show_past_events:
      type: boolean
      label: 'Show Past Events'
    events_per_page:
      type: integer
      label: 'Number of Events per Page'
