version: '3.8'

services:
  # PHP and Drupal app container
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    image: drupal_php
    container_name: drupal_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - drupal-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=drupal
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  # MySQL database container
  db:
    image: mysql:8.0
    container_name: drupal_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set root password
      MYSQL_DATABASE: drupal     # Optional: create a database on startup
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - drupal-network

  # Nginx container
  webserver:
    image: nginx:alpine
    container_name: drupal_webserver
    ports:
      - "4444:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - drupal-network
    depends_on:
      - drupal

networks:
  drupal-network:

volumes:
  dbdata:
