version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal-network

  web:
    build: .
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - drupal-network

volumes:
  db_data:

networks:
  drupal-network:
    driver: bridge
